version: '3'

services:
  db:
    image: mfashby/ysc-mysql-demo
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  api-server:
    image: mfashby/ysc-apiserver-demo
    build: sailracetimerserver
    environment:
     - DB_URL=jdbc:mysql://db:3306/yxsecnyo_ysc
     - DB_USER=root
     - DB_PASS=example
     - SVR_PORT=80
     - SVR_HOST=0.0.0.0

  front:
    image: mfashby/ysc-front-demo
    build: front
    environment:
     - "EXTERNAL_URL=localhost:8080"
     - "TLS_CONFIG=off"
    ports:
     - 8080:8080

  adminer:
    image: adminer
    ports: 
     - 8081:8080
