version: '2'

services:
  db:
    image: mfashby/ysc-mysql
    build: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  api-server:
    image: mfashby/ysc-apiserver
    build: sailracetimerserver
    environment:
      - DB_URL=jdbc:mysql://db:3306/yxsecnyo_ysc
      - DB_USER=root
      - DB_PASS=example
      - SVR_PORT=80
      - SVR_HOST=0.0.0.0
    links:
      - db:db

  front:
    image: mfashby/ysc-front
    build: front
    environment:
     - "EXTERNAL_URL=localhost:8080"
     - "TLS_CONFIG=off"
    ports:
      - 8080:8080
